# Generated by Django 4.1.6 on 2023-02-06 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000)),
                ('pub_date', models.DateField(default=datetime.datetime(2023, 2, 6, 14, 58, 5, 895588))),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
    ]
