# Generated by Django 4.1.6 on 2023-02-09 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_comment_alter_post_pub_date_delete_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 9, 17, 5, 55, 604346)),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 9, 17, 5, 55, 603346)),
        ),
    ]
