# Generated by Django 4.1.6 on 2023-02-14 14:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_remove_comment_likes_alter_comment_pub_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 14, 15, 31, 50, 876287)),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 14, 15, 31, 50, 875286)),
        ),
    ]
