# Generated by Django 4.1.6 on 2023-02-17 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_alter_comment_pub_date_alter_post_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 17, 15, 57, 43, 855983)),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 17, 15, 57, 43, 854968)),
        ),
    ]
