# Generated by Django 4.1.6 on 2023-02-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialuser',
            name='bio',
            field=models.CharField(default='', max_length=256),
        ),
    ]
