# Generated by Django 4.1.6 on 2023-02-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_socialuser_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialuser',
            name='photo',
            field=models.ImageField(default='s', upload_to=''),
            preserve_default=False,
        ),
    ]
